M48
; DRILL file {KiCad (6.0.5-0)} date Saturday, August 06, 2022 at 12:04:22 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-06T12:04:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.55Y-4.05
X3.55Y-4.5
X3.55Y-4.85
X3.55Y-5.3
T0
M30
