M48
; DRILL file {KiCad (6.0.6)} date Sun Aug  7 11:28:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-07T11:28:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.4514Y-3.7986
X2.4514Y-4.2486
X2.4514Y-4.5986
X2.4514Y-5.0486
T0
M30
